[tool.poetry]
name = "seadog"
version = "0.1.0"
description = ""
authors = ["leonhfr <hello@leonh.fr>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
