[tool.poetry]
name = "seadog"
version = "0.1.0"
description = "Statistical data visualization from the command line"
authors = ["leonhfr <hello@leonh.fr>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
numpy = "^1.18.0"
pandas = "^0.25.3"
matplotlib = "^3.1.2"
seaborn = "^0.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
